version: '3.9'

services:
  mysql:
    container_name: mysql
    image: mysql:8.2.0
    platform: linux/amd64
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=howard
      - MYSQL_DATABASE=howard
      - MYSQL_USER=howard
      - MYSQL_PASSWORD=howard
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - db-network

  order-system:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    ports: 
      - 3000:3000
    environment:
      - MYSQL_HOST=mysql
    networks:
      - db-network

volumes:
  db-data:
    name: mysql-data
networks:
  db-network:
    name: db-network